
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "b2084fa1b9a9932a221e70b6becf5cc634a86974",
 "version": "1.18.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
